### PR TITLE
Add an LTS 11 snapshop

### PR DESCRIPTION
**Pull request by tonyd256**
Creating an lts-11 snapshot so we can use the latest GHC and libraries.

I'm not sure how to make sure that this will work for all our projects, so
please let me know if I can test/build any projects to verify.

### CODE REVIEW

**Review by mfine — COMMENTED** [review]
Hope this works - 11 has some breaking changes in conduits and other areas. Probably need to remove wolf from the packages.

**Comment by mfine** [comment]
You can verify if things are building with:

```
$ stack build --resolver lts-11.15 gnss-converters-0.3.44 labsat-0.0.5 postgresql-connector-0.2.5 preamble-0.0.61 rtcm-0.2.17 sbp-2.3.16 serialport-0.4.7 shakers-0.0.48 warped-0.0.5 wolf-0.3.45
```

**Review by rastislav-swift — COMMENTED** [review]
I think this is OK, majority of stuff I'm aware of uses fixed 0.0.32 release, as we build cached images around it and stuff, so we should not be affected by this

**Comment by rastislav-swift** [comment]
@tonyd256 Is there any particular feature you need from LTS-11.15? If not, maybe you can use older release as dependency?

**Comment by mfine** [comment]
this works:

```$ stack build --resolver lts-11.15 postgresql-connector-0.2.5 preamble-0.0.61 rtcm-0.2.17 sbp-2.3.16 serialport-0.4.7 shakers-0.0.48 warped-0.0.5```

**Comment by tonyd256** [comment]
@mfine @rastislav-swift Ok so it sounds like things using this are pinned to a version so adding this file isn't going to break any existing changes. So this is ok to merge?

**Comment by mfine** [comment]
can you just restrict it to:

```
- postgresql-connector-0.2.5
- preamble-0.0.61
- rtcm-0.2.17
- sbp-2.3.16
- serialport-0.4.7
- shakers-0.0.48
- warped-0.0.5
```

then it should be good to be brought it.

**Comment by mfine** [comment]
sweet, thanks for bringing this in.

**Pull request merged**
